-
  before_text: Go to a pub
  after_text: Cool party
  conds:
    -
      field: money
      operator: '>'
      value: 10
  effects:
    -
      field: money
      operator: '-'
      value: 10
    -
      field: mana
      operator: '+'
      value: 10
    -
      field: cheerfulness
      operator: '+'
      value: 20
-
  before_text: Go to work
  after_text: Borning routine
  conds:
    -
      field: mana
      operator: '<'
      value: 50
    -
      field: fatigue
      operator: '<'
      value: 10
  effects:
    -
      field: 'money'
      operator: '+'
      value: '100'
    -
      field: 'fatigue'
      operator: '+'
      value: '70'
    -
      field: 'cheerfulness'
      operator: '-'
      value: '5'
    -
      field: 'mana'
      operator: '-'
      value: '30'
-
  before_text: Contemplate nature
  after_text: Nice nature
  effects:
    -
      field: cheerfulness
      operator: '+'
      value: 1
    -
      field: mana
      operator: '-'
      value: 10
    -
      field: fatigue
      operator: '+'
      value: 10
-
  before_text: Drink wino and watch a seriels
  after_text: I am relaxed
  effects:
    -
      field: cheerfulness
      operator: '-'
      value: 1
    -
      field: mana
      operator: '+'
      value: 30
    -
      field: fatigue
      operator: '+'
      value: 10
    -
      field: health
      operator: '-'
      value: 5
    -
      field: money
      operator: '-'
      value: 20
-
  before_text: Drink with marginals
  after_text: I AM DRUNK IN SH*T
  effects:
    -
      field: cheerfulness
      operator: '+'
      value: 5
    -
      field: health
      operator: '-'
      value: 80
    -
      field: mana
      operator: '+'
      value: 90
    -
      field: fatigue
      operator: '+'
      value: 80
    -
      field: money
      operator: '-'
      value: 150
-
  before_text: Sing in subway
  after_text: Cool time
  effects:
    -
      field: cheerfulness
      operator: '+'
      value: 1
    -
      field: mana
      operator: '+'
      value: 10
    -
      field: money
      operator: '+'
      value: 10
    -
      field: fatigue
      operator: '+'
      value: 20
-
  before_text: Sing in subway
  after_text: Cool time
  conds:
    -
      field: mana
      operator: '>'
      value: 40
    -
      field: mana
      operator: '<'
      value: 70
  effects:
    -
      field: cheerfulness
      operator: '+'
      value: 1
    -
      field: mana
      operator: '+'
      value: 10
    -
      field: money
      operator: '+'
      value: 50
    -
      field: fatigue
      operator: '+'
      value: 20
-
  before_text: Sleep
  after_text: I rested
  conds:
    -
      field: mana
      operator: '<'
      value: 30
  effects:
    -
      field: health
      operator: '+'
      value: 30
    -
      field: mana
      operator: '-'
      value: 50
    -
      field: fatigue
      operator: '-'
      value: 70
-
  before_text: Sleep
  after_text: I rested
  conds:
    -
      field: mana
      operator: '>'
      value: 70
  effects:
    -
      field: cheerfulness
      operator: '-'
      value: 3
    -
      field: mana
      operator: '-'
      value: 50
    -
      field: fatigue
      operator: '-'
      value: 70
-
  before_text: Sleep
  after_text: I rested
  effects:
    -
      field: mana
      operator: '-'
      value: 50
    -
      field: fatigue
      operator: '-'
      value: 70